/** @type {import('tailwindcss').Config} */
const includePreflight = 'editor' === process.env._TW_TARGET ? false : true;

module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './theme/**/*.php',
  ],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        'black': '#121212',
        'dark': '#121212',
        'red': '#DB3327',
        'grey': '#525252',
        'grey-light': '#E0E0E0',
        'grey-lighter': '#F7F7F7',
        'hightlight': '#F2F2F2',
        'disabled': '#BDBDBD'
      },
	  keyframes: {
		fadeInOut: {
			'0%': { opacity: 0 },
			'100%': { opacity: 1 }
		}
	  },
	  animation: {
		fadeInOut: 'fadeInOut 500ms ease-in-out forwards'
	  },
      height: () => ({
        'header': 'var(--header-height)',
        'header-compact': 'var(--header-compact-height)',
        'screen-safe-header': 'calc(var(--inner-height) - var(--header-height))',
        'screen-safe': 'var(--inner-height)'
      }),
      backgroundImage: {
        'hero-pattern': "url('/img/hero-pattern.svg')",
        'latest-overlay': "linear-gradient(180deg, rgba(255, 255, 255, 0.00) 0%, #FFF 100%)",
      }
    },
    borderWidth: {
      DEFAULT: '1px',
      '0': '0',
      '1': '1px',
      '2': '2px',
      '3': '3px',
      '4': '4px',
      '6': '6px',
      '8': '8px',
    },
    screens: {
      mobile: '0px',
      mobilexl: '600px',
      tablet: '834px',
      newsletter: '880px',
      laptop: '1024px',
      desktopsm: '1360px',
      desktop: '1440px',
      large: '1920px',
      huge: '2400px'
    },
    containers: {
      mobile: '0px',
      tablet: '834px',
      newsletter: '880px',
      laptop: '1024px',
      desktop: '1440px',
      large: '1920px',
      huge: '2400px'
    },
    spacing: {
      'header': 'var(--header-height)',
      'header-compact': 'var(--header-compact-height)',
      '0': '0',
      '1': '1px',
      '2': '2px',
      '3': '3px',
      '4': '4px',
      '5': '5px',
      '6': '6px',
      '7': '7px',
      '8': '8px',
      '9': '9px',
      '10': '10px',
      '11': '11px',
      '12': '12px',
      '14': '14px',
      '15': '15px',
      '16': '16px',
      '18': '18px',
      '20': '20px',
      '23': '23px',
      '24': '24px',
      '25': '25px',
      '28': '28px',
      '30': '30px',
      '32': '32px',
      '35': '35px',
      '36': '36px',
      '38': '38px',
      '40': '40px',
      '42': '42px',
      '45': '45px',
      '48': '48px',
      '50': '50px',
      '52': '52px',
      '55': '55px',
      '58': '58px',
      '60': '60px',
      '64': '64px',
      '65': '65px',
      '68': '68px',
      '70': '70px',
      '72': '72px',
      '75': '75px',
      '80': '80px',
      '85': '85px',
      '90': '90px',
      '95': '95px',
      '100': '100px',
      '110': '110px',
      '114': '114px',
      '120': '120px',
      '130': '130px',
      '140': '140px',
      '150': '150px',
      '160': '160px',
      '170': '170px',
      '180': '180px',
      '190': '190px',
      '200': '200px',
      '250': '250px',
      '1/2':'50%'
    },
    fontFamily: {
      'sans': "'National', Helvetica, Arial, sans-serif",
      'serif': "'Ivar', 'Times New Roman', Times, serif",
      'georgia': "georgiapro, Georgia, serif",
      'grotesk': "RightGrotesk, sans-serif",
    },
    fontWeight: {
      thin: '100',
      hairline: '100',
      extralight: '200',
      light: '300',
      lightmedium: '350',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      'extra-bold': '800',
      black: '900',
    },
    fontSize: {
      '5xl': '100px',
      '4xl': '44px',
      '3xl': '40px',
      '2xl': '36px',
      'xl': '32px',
      'lg': '30px',
      'mdl': '26px',
      'mdm': '22px',
      'md': '20px',
      'reg': '18px',
      'base': '18px',
      'sml': '17px',
      'smm': '16px',
      'smx': '15px',
      'sm': '14px',
      'xm': '13px',
      'xs': '12px'
    },
    lineHeight: {
      '5xl': '84px',
      '4xl': '48px',
      '3xlm': '45px',
      '3xl': '44px',
      '2xl': '43px',
      'xll': '41px',
      'xlm': '38px',
      'xl': '36px',
      'lg': '34px',
      'mdl': '32px',
      'md': '24px',
      'reg': '23px',
      'base': '28px',
      'smxxl': '22px',
      'smxl': '20px',
      'sml': '19px',
      'smm': '18px',
      'sm': '18px',
      'smx': '17px',
      'xm': '16px',
      'xs': '14px',
      'normal': '1'
    },
  },
  corePlugins: {
		// Disable Preflight base styles in builds targeting the editor.
		preflight: includePreflight,
	},
  plugins: [
    require('@_tw/themejson'),
    // require('@tailwindcss/typography'),
	  require('@tailwindcss/container-queries')
  ],
}
